# Download MySql Workbench:
# https://www.mysql.com/products/workbench/
# Install Service:
# docker stack deploy -c docker-compose.yml pat
# docker service scale pat_mysql=0

version: '3.5'

services:
  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "PassW@r6"
    volumes:
      - mysql-datavolume:/var/lib/mysql

volumes:
  mysql-datavolume:
